$schema: "https://json-schema.org/draft-04/schema"
$id: "https://micinfotech.com/glossary/import-config.schema.json"
title: Import Config
description: "import configure file, import tool will work base it."
type: object
properties:
  inputs:
    type: array
    items:
      type: object
      properties:
        path:
          type: string
        jsonPath:
          type: array
          items:
            anyOf:
              - type: string
              - type: number
        isWholeJson:
          type: boolean
        replaces:
          type: object
          properties:
            pattern: string
            flags: string
            newstr: string
          required:
            - pattern
        test:
          type: object
          properties:
            pattern: string
            flags: string
          required:
            - pattern
        separator:
          type: string
      required:
        - path
  outputPath:
    type: string
  ingoreSpellCheck:
    type: boolean
  debug:
    type: boolean
required:
  - inputs
